# This action builds and tests a basic image, as described here:
# https://canonical-risc-v-cookbook.readthedocs-hosted.com/en/latest/tutorial/create_image/
name: Build and test

# We allow running workflows on main, and on the 'ci' special branch used to work
# on ci/cd workflows.
on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install apt dependencies
        run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y snapd qemu-user-static ubuntu-dev-tools
      - name: Refresh systemd-binfmt
        run: sudo systemctl restart systemd-binfmt
      - name: Install ubuntu-image
        run: sudo snap install --classic ubuntu-image
      - name: Build image
        run: sudo ubuntu-image --workdir work --debug classic image-definition.yaml
      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04-preinstalled-server-riscv64.img
          path: work/ubuntu-24.04-preinstalled-server-riscv64.img
      - name: Upload manifest as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04-preinstalled-server-riscv64.manifest
          path: work/ubuntu-24.04-preinstalled-server-riscv64.manifest
